/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main_GameBoard */

#ifndef _Included_Main_GameBoard
#define _Included_Main_GameBoard
#ifdef __cplusplus
extern "C" {
#endif
#undef Main_GameBoard_FOCUS_TRAVERSABLE_UNKNOWN
#define Main_GameBoard_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Main_GameBoard_FOCUS_TRAVERSABLE_DEFAULT
#define Main_GameBoard_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Main_GameBoard_FOCUS_TRAVERSABLE_SET
#define Main_GameBoard_FOCUS_TRAVERSABLE_SET 2L
#undef Main_GameBoard_TOP_ALIGNMENT
#define Main_GameBoard_TOP_ALIGNMENT 0.0f
#undef Main_GameBoard_CENTER_ALIGNMENT
#define Main_GameBoard_CENTER_ALIGNMENT 0.5f
#undef Main_GameBoard_BOTTOM_ALIGNMENT
#define Main_GameBoard_BOTTOM_ALIGNMENT 1.0f
#undef Main_GameBoard_LEFT_ALIGNMENT
#define Main_GameBoard_LEFT_ALIGNMENT 0.0f
#undef Main_GameBoard_RIGHT_ALIGNMENT
#define Main_GameBoard_RIGHT_ALIGNMENT 1.0f
#undef Main_GameBoard_serialVersionUID
#define Main_GameBoard_serialVersionUID -7644114512714619750i64
#undef Main_GameBoard_serialVersionUID
#define Main_GameBoard_serialVersionUID 4613797578919906343i64
#undef Main_GameBoard_INCLUDE_SELF
#define Main_GameBoard_INCLUDE_SELF 1L
#undef Main_GameBoard_SEARCH_HEAVYWEIGHTS
#define Main_GameBoard_SEARCH_HEAVYWEIGHTS 1L
#undef Main_GameBoard_NOT_OBSCURED
#define Main_GameBoard_NOT_OBSCURED 0L
#undef Main_GameBoard_PARTIALLY_OBSCURED
#define Main_GameBoard_PARTIALLY_OBSCURED 1L
#undef Main_GameBoard_COMPLETELY_OBSCURED
#define Main_GameBoard_COMPLETELY_OBSCURED 2L
#undef Main_GameBoard_WHEN_FOCUSED
#define Main_GameBoard_WHEN_FOCUSED 0L
#undef Main_GameBoard_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define Main_GameBoard_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef Main_GameBoard_WHEN_IN_FOCUSED_WINDOW
#define Main_GameBoard_WHEN_IN_FOCUSED_WINDOW 2L
#undef Main_GameBoard_UNDEFINED_CONDITION
#define Main_GameBoard_UNDEFINED_CONDITION -1L
#undef Main_GameBoard_IS_DOUBLE_BUFFERED
#define Main_GameBoard_IS_DOUBLE_BUFFERED 0L
#undef Main_GameBoard_ANCESTOR_USING_BUFFER
#define Main_GameBoard_ANCESTOR_USING_BUFFER 1L
#undef Main_GameBoard_IS_PAINTING_TILE
#define Main_GameBoard_IS_PAINTING_TILE 2L
#undef Main_GameBoard_IS_OPAQUE
#define Main_GameBoard_IS_OPAQUE 3L
#undef Main_GameBoard_KEY_EVENTS_ENABLED
#define Main_GameBoard_KEY_EVENTS_ENABLED 4L
#undef Main_GameBoard_FOCUS_INPUTMAP_CREATED
#define Main_GameBoard_FOCUS_INPUTMAP_CREATED 5L
#undef Main_GameBoard_ANCESTOR_INPUTMAP_CREATED
#define Main_GameBoard_ANCESTOR_INPUTMAP_CREATED 6L
#undef Main_GameBoard_WIF_INPUTMAP_CREATED
#define Main_GameBoard_WIF_INPUTMAP_CREATED 7L
#undef Main_GameBoard_ACTIONMAP_CREATED
#define Main_GameBoard_ACTIONMAP_CREATED 8L
#undef Main_GameBoard_CREATED_DOUBLE_BUFFER
#define Main_GameBoard_CREATED_DOUBLE_BUFFER 9L
#undef Main_GameBoard_IS_PRINTING
#define Main_GameBoard_IS_PRINTING 11L
#undef Main_GameBoard_IS_PRINTING_ALL
#define Main_GameBoard_IS_PRINTING_ALL 12L
#undef Main_GameBoard_IS_REPAINTING
#define Main_GameBoard_IS_REPAINTING 13L
#undef Main_GameBoard_WRITE_OBJ_COUNTER_FIRST
#define Main_GameBoard_WRITE_OBJ_COUNTER_FIRST 14L
#undef Main_GameBoard_RESERVED_1
#define Main_GameBoard_RESERVED_1 15L
#undef Main_GameBoard_RESERVED_2
#define Main_GameBoard_RESERVED_2 16L
#undef Main_GameBoard_RESERVED_3
#define Main_GameBoard_RESERVED_3 17L
#undef Main_GameBoard_RESERVED_4
#define Main_GameBoard_RESERVED_4 18L
#undef Main_GameBoard_RESERVED_5
#define Main_GameBoard_RESERVED_5 19L
#undef Main_GameBoard_RESERVED_6
#define Main_GameBoard_RESERVED_6 20L
#undef Main_GameBoard_WRITE_OBJ_COUNTER_LAST
#define Main_GameBoard_WRITE_OBJ_COUNTER_LAST 21L
#undef Main_GameBoard_REQUEST_FOCUS_DISABLED
#define Main_GameBoard_REQUEST_FOCUS_DISABLED 22L
#undef Main_GameBoard_INHERITS_POPUP_MENU
#define Main_GameBoard_INHERITS_POPUP_MENU 23L
#undef Main_GameBoard_OPAQUE_SET
#define Main_GameBoard_OPAQUE_SET 24L
#undef Main_GameBoard_AUTOSCROLLS_SET
#define Main_GameBoard_AUTOSCROLLS_SET 25L
#undef Main_GameBoard_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define Main_GameBoard_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef Main_GameBoard_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define Main_GameBoard_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     Main_GameBoard
 * Method:    setupGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_GameBoard_setupGame
  (JNIEnv *, jobject);

/*
 * Class:     Main_GameBoard
 * Method:    handleClick
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Main_GameBoard_handleClick
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Main_GameBoard
 * Method:    getTileInformation
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Main_GameBoard_getTileInformation
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
